title: znb.kz
description: for documentation.

# Development server config, needed to load some of the content
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Theme settings
site_author: nur76n
repo_url: 'https://github.com/nur76n/nur76n.github.io'
edit_on_github: false
github_docs_folder: false
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: true
hljs_style: github-gist
